package com.example.gohike.connection

enum class ConnectionThreadEventType {
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,

    LOGOUT_REQUEST,

    REGISTRATION_REQUEST,
    REGISTRATION_SUCCESS,
    REGISTRATION_FAILURE,

    PROFILE_REQUEST,
    PROFILE_RETRIEVAL_SUCCESS,
    PROFILE_RETRIEVAL_FAILURE,
    PROFILE_SAVE,

    ROUTES_REQUEST,
    ROUTES_RETRIEVAL_SUCCESS,
    ROUTES_RETRIEVAL_FAILURE,

    ROUTE_REQUEST,
    ROUTE_RETRIEVAL_SUCCESS,
    ROUTE_RETRIEVAL_FAILURE,
    ROUTE_SAVE
}